src/core/Player.ts, src/core/events/player-events.ts, src/core/index.ts, src/core/strategies/boot/BootStrategy.ts, src/core/strategies/boot/BootStrategyFactory.ts, src/core/strategies/boot/Bootable.ts, src/core/strategies/boot/ClickBootStrategy.ts, src/core/strategies/boot/ImmediateBootStrategy.ts, src/core/strategies/boot/LazyBootStrategy.ts, src/core/strategies/boot/index.ts, src/core/strategies/boot/tests/boot-strategy.test.ts, src/core/strategies/index.ts, src/core/tests/player-boot.test.ts, src/utils/network.ts, src/utils/support.ts
=> feat: boot strategy

src/core/provider/MockMediaProvider.ts, src/core/provider/vds-mock-media-provder.ts
=> feat: mock media provider

package-lock.json, package.json, src/core/mixins/tests/context-mixin.test.ts, src/core/player.events.ts, src/core/provider/MediaProvider.ts, src/core/user/user.events.ts, src/providers/file/MediaFileProvider.ts, src/providers/hls/HlsProvider.ts, src/providers/hls/hls.events.ts, src/providers/hls/hls.stories.ts, src/providers/hls/hls.types.ts, src/providers/hls/hls.utils.ts, src/providers/hls/index.ts, src/providers/hls/vds-hls.ts, src/providers/video/VideoProvider.ts, src/providers/video/video.args.ts, src/providers/video/video.css.ts, src/providers/video/video.stories.ts, src/shared/LibLoader.ts, src/shared/directives/if-non-null.ts, src/shared/directives/if-number.ts
=> feat: hls provider

src/providers/file/MediaFileProvider.ts, src/providers/hls/HlsProvider.ts, src/providers/video/VideoProvider.ts, src/providers/video/index.ts, src/ui/ui/Ui.ts, src/ui/ui/index.ts, src/ui/ui/tests/ui.test.ts, src/ui/ui/ui.css.ts, src/ui/ui/vds-ui.ts
=> feat(ui/ui): new ui component

src/providers/video/VideoProvider.ts, src/ui/controls/control/Control.ts, src/ui/controls/toggle/Toggle.ts, src/ui/controls/toggle/index.ts, src/ui/controls/toggle/tests/toggle.test.ts, src/ui/controls/toggle/toggle.css.ts, src/ui/controls/toggle/vds-toggle.ts, src/ui/ui/Ui.ts, src/utils/dom.ts
=> feat(providers/controls/toggle): new toggle component

src/bundle/elements.ts, src/bundle/index.ts, src/core/user/user.events.ts, src/ui/controls/control/Control.ts, src/ui/controls/playback-toggle/PlaybackToggle.ts, src/ui/controls/playback-toggle/index.ts, src/ui/controls/playback-toggle/tests/playback-toggle.test.ts, src/ui/controls/playback-toggle/vds-playback-toggle.ts, src/ui/controls/toggle/Toggle.ts, src/ui/ui/Ui.ts
closes #30, closes #31, closes #32
=> feat: new playback toggle component

src/bundle/elements.ts, src/bundle/index.ts, src/core/player.context.ts, src/ui/controls/mute-toggle/MuteToggle.ts, src/ui/controls/mute-toggle/index.ts, src/ui/controls/mute-toggle/tests/mute-toggle.test.ts, src/ui/controls/mute-toggle/vds-mute-toggle.ts
=> feat: new mute toggle component

src/bundle/elements.ts, src/bundle/index.ts, src/core/provider/MediaProvider.ts, src/ui/buffering-indicator/BufferingIndicator.ts, src/ui/buffering-indicator/buffering-indicator.css.ts, src/ui/buffering-indicator/buffering-indicator.events.ts, src/ui/buffering-indicator/index.ts, src/ui/buffering-indicator/tests/buffering-indicator.test.ts, src/ui/buffering-indicator/vds-buffering-indicator.ts, src/utils/dom.ts
=> feat: new buffering indicator component

src/core/fakes/FakeContextConsumer.ts, src/core/mixins/PlayerContextMixin.ts, src/core/player.context.ts, src/core/player.events.ts, src/core/player.types.ts, src/core/provider/MediaProvider.ts, src/providers/file/MediaFileProvider.ts, src/providers/hls/hls.stories.ts, src/providers/video/VideoProvider.ts, src/providers/video/video.args.ts, src/providers/video/video.stories.ts
=> feat: loop support

src/bundle/elements.ts, src/bundle/index.ts, src/core/fakes/FakeMediaProvider.ts, src/core/provider/MediaProvider.ts, src/providers/video/VideoProvider.ts, src/shared/directives/FocusMixin.ts, src/ui/controls/scrubber/Scrubber.ts, src/ui/controls/scrubber/index.ts, src/ui/controls/scrubber/scrubber.args.ts, src/ui/controls/scrubber/scrubber.css.ts, src/ui/controls/scrubber/scrubber.stories.ts, src/ui/controls/scrubber/tests/scrubber.test.ts, src/ui/controls/scrubber/vds-scrubber.ts, src/ui/controls/slider/Slider.ts, src/ui/controls/slider/slider.args.ts, src/ui/controls/slider/slider.css.ts, src/ui/controls/slider/slider.stories.ts, src/ui/controls/slider/tests/slider.test.ts
=> feat: new scrubber component

package-lock.json, package.json, src/core/ScreenOrientation.ts, src/core/fakes/FakeContextConsumer.ts, src/core/index.ts, src/core/player.context.ts, src/core/player.events.ts, src/core/player.types.ts, src/core/provider/MediaProvider.ts, src/providers/video/VideoProvider.ts, src/shared/types.ts, src/ui/ui/Ui.ts, src/utils/support.ts
=> feat: fullscreen support

src/core/fakes/FakeMediaProvider.ts, src/core/player.context.ts, src/core/player.events.ts, src/core/player.types.ts, src/core/provider/MediaProvider.ts, src/core/provider/provider.args.ts, src/core/user/tests/user-events.test.ts, src/core/user/user.events.ts, src/providers/hls/hls.stories.ts, src/providers/video/VideoProvider.ts, src/providers/video/video.stories.ts, src/ui/controls/fullscreen-toggle/FullscreenToggle.ts, src/ui/controls/fullscreen-toggle/fullscreen-toggle.args.ts, src/ui/controls/fullscreen-toggle/fullscreen-toggle.stories.ts, src/ui/controls/fullscreen-toggle/fullscreen-toggle.types.ts, src/ui/controls/fullscreen-toggle/tests/fullscreen-toggle.test.ts, src/ui/controls/fullscreen-toggle/vds-fullscreen-toggle.ts, src/ui/controls/mute-toggle/mute-toggle.args.ts, src/ui/controls/scrubber/Scrubber.ts, src/ui/controls/scrubber/scrubber.args.ts
=> feat: new toggle fullscreen component

src/media/controller/MediaControllerElement.js, src/media/controller/tests/element.test.js
=> fix(media/controller): call seek on media when seeking request received

src/media/provider/MediaProviderElement.js
=> fix(media/controller): fullscreen property not reflecting true state

.storybook/main.js, src/foundation/types/patch.ts, src/providers/hls/HlsElement.js, src/providers/hls/element.stories.js, src/providers/hls/events.js, src/providers/html5/Html5MediaElement.js, src/utils/network.js, src/utils/support.js
=> feat: stage-1 of progressively enhanced hls support

src/media/controller/tests/element.test.js, src/media/provider/tests/props.test.js
Hi man, 
Sorry for this being the first commit here, just following along the process and caught this typo. Had it correctly spelled in the commit title though! haha
PS: If help is needed in writing or proofreading docs down the road, let me know. Would love to help some! 💪🏼
=> style: fix typo "immuatable" to "immutable"

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md
**Is your feature request related to a problem? Please describe.**
As you start to get more contributions, it might be easier to have templates for PRs and Issues.
**Describe the solution you'd like**
These are some of the templates I've been using in some of the Open Source projects I've worked on, hope this helps.
**Additional context**
_Totally optional, no worries if you are not into it._
_Also let me know if since you are using github discussions you'd rather not have a template for feature requests in github issues (although is easy to convert issues into discussions etc...)_
=> GitHub PR & Issue templates

apps/site/app/docs/[lib]/player/[2]core-concepts/[7]skins/page.md
Slight modification to docs.
Added a note to clarify that the player changes its UI in response to certain size breakpoints.
Yes.
=> Added note about size breakpoints

packages/vidstack/src/components/ui/sliders/time-slider/slider-chapters.ts
=> fix(player): get correct chapter start index 

packages/vidstack/src/components/ui/sliders/time-slider/slider-chapters.ts
Closes #1499 
Feel free to make any changes, thanks.
=> fix(player) Unrelated chapter is shown while cursor is leaving the timeline
