vidstack/player

- .gitignore
.link is used as a link folder for yarn/npm link when developing within a mounted volume.
> chore: add .link to .gitignore

- src/core/strategies/boot/BootStrategyFactory.ts
Simple refactoring to differentiate between `BootStrategyType` and a `CustomBootStrategy`. Allows a cleaner reference to the strings the factory accepts to build certain strategies such as `'immediate'`, `'click'` etc.
> refactor: BootStrategyFactory

- src/core/Player.ts
- src/core/player.context.ts
- src/core/player.events.ts
- src/core/player.types.ts
- src/core/tests/FakeConsumer.ts
- src/core/tests/helpers.ts
- src/core/tests/player-misc.test.ts
- src/core/tests/player-props.test.ts
- src/utils/dom.ts
- src/utils/test/dom.test.ts
CSS Media Queries combined with Media Features solves the issue of styling independently between mouse/touch. If this API is required we can bring it back in a future release.
BREAKING CHANGE:
The following player properties/context/events were removed:
- `inputDevice`
- `isTouchInputDevice`
- `isMouseInputDevice`
- `isKeyboardInputDevice`
- `vds-input-device-change`
The following were removed from `utils/dom`:
- `InputDevice`
- `onInputDeviceChange`
> refactor: remove input device api

- src/ui/controls/playback-toggle/PlaybackToggle.ts
- src/ui/controls/playback-toggle/tests/playback-toggle.test.ts
It appears you made a simple (and very common) oversight in the naming of the slots.
This is one reason I personally prefer active properties like `playing`. It feels more natural to me when `true` reflects the active state. Paused feels "off" > 0 > false. Playing feels "on" > 1 > true. 🤷‍♂️
> reverse inverted slot names for pause and play

- src/ui/buffering-indicator/BufferingIndicator.ts
The indicator was lingering once playback resumed. It should be dismissed immediately.
> only use delay when displaying indicator

- global.d.ts
- src/base/observers/IntersectionController.ts
- src/base/observers/PageController.ts
- src/base/observers/index.ts
- src/base/observers/intersection-controller.story.svelte
- src/base/observers/page-controller.story.svelte
- src/define/vds-media-sync.ts
- src/define/vds-media-visibility.ts
- src/global/types.ts
- src/index.ts
- src/media/controller/MediaController.ts
- src/media/index.ts
- src/media/manage/MediaSyncElement.ts
- src/media/manage/MediaVisibilityElement.ts
- src/media/manage/events.ts
- src/media/manage/index.ts
- src/media/manage/media-sync.story.svelte
- src/media/manage/media-visibility.story.svelte
- src/media/provider/MediaProviderElement.ts
Management includes:
- Page visibility changes (ie: user changes tab or device sleeps).
- Viewport visibility changes (ie: user scrolls video in and out of view).
- Shared playback (ie: user plays a video while another is already playing). 
- Shared volume (ie: user sets desired volume to 50% on one player and they expect it to be consistent across all players).
There’s different responsibilities being tackled here, so the best solution might be to build these out as controllers (eg: `PageVisibilityController`). These controllers could also be attached to a corresponding element such as `vds-media-manager`, or maybe `vds-page-manager`/`vds-viewport-manager` (if we want separate elements). 
- **new:** `IntersectionController` for observing viewport intersection on a given `host` element.
- …
> feat: media management

- packages/player/src/ui/slider/SliderElement.ts
when the `min` of slider element is set to value larger than 0, the fill rate and pointer rate may exceed 1, thereby causing styling issues, this PR should fix this issue. 
For example: 
https://github.com/vidstack/player/blob/34ee665fd44cfdcb99813cee7730a25e892b3e24/src/ui/slider/SliderElement.ts#L203-L206
```js
/**
* The current value to range ratio.
*
* @default 0.5
* @example
* `min` = 9
* `max` = 10
* `value` = 9
* `range` = 1 (max - min)
* `fillRate` = 9 (result)
*/
get fillRate(): number {
const range = this.max - this.min;
return range > 0 ? this.value / range : 0;
}
```
> Fix unexpected fill rate and pointer rate`SliderElement` when `min` > 0

- apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[7]play-button/_snippets/replay.css
- apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[7]play-button/_snippets/replay.html
- apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[7]play-button/_snippets/replay.jsx
- apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[7]play-button/index.md
- package.json
- turbo.json
https://github.com/vidstack/player/issues/680
Ready
_NA_
Let me know if you'd prefer it without the example
> Docs: media `ended` fix + example

- apps/site/pages/docs/player/[lib]/[2]components/@markdoc/component_import.svelte
- apps/site/pages/docs/player/[lib]/[2]components/@markdoc/component_tabbed_links.svelte
https://github.com/vidstack/player/issues/682
Aims to remove import code snippet for  buffering indicator a and controls page
Not ready
_NA_
I did the change suggested in https://github.com/vidstack/player/issues/682#issuecomment-1304704202 but I don't see it when I run the preview of the site locally. Not sure I did the change correctly?
> docs(site): remove import code snippet for  buffering indicator a and controls page

- apps/site/pages/docs/player/[lib]/[2]components/[3]ui/[7]play-button/_snippets/styling.css
in the same space of https://github.com/vidstack/player/discussions/693 but not directly related
Tiny PR to fix styling example page for [`Poster`](https://www.vidstack.io/docs/player/react/components/ui/poster/#styling)
Ready 
Before - you can't properly see the play icon
After
> docs(player): fix styling example page for Poster

- packages/vidstack/src/player/ui/slider-video/element.tsx
This PR adds a check for `$slider.pointerRate` to be finite in the slider-video component.
Yes, this PR is ready to be reviewed.
Ensure "double value is non-finite" error is not observed again
> fix: add isFinite check for pointer rate on slider-video

- packages/vidstack/src/utils/time.test.ts
This PR fixes build errors that can be seen on #835 and #810 
This PR changes the time tests to match the current specification and expected results.
Yes, this PR is ready to be reviewed.
N/A
```
$ pnpm run test
```
> fix: time tests match current specification

- packages/vidstack/styles/ui/menus.css
I'm using this library with Hugo's built-in SCSS capabilities (in Dart SASS mode to support the latest features), however it complained about a missing selector in `menus.css` file. When I opened it in the IDE, even that was showing a syntax error where I have made the changes. This PR should fix that issue.
While I understand a new version is being shipped, it would be useful if this PR is merged and released while the docs for the new version are prepared.
Yes
No
Simply removing an extra comma, nothing much to review here
> fix: SCSS compilation with Dart SASS

- packages/vidstack/src/providers/vimeo/loader.ts
When I tried to start the project it gave me an error related to `/packages/vidstack/src/providers/vimeo/loader.ts` file that `info` is `undefined` so I opened the file and saw the ts error that says `'info' is possibly 'undefined'`. This error prevents the project  to start.
Yes
> fix vimeo loader file type error

- packages/vidstack/player/styles/default/layouts/video.css
Using SCSS to transform CSS fails with the error: `failed to transform "css/bundle.scss" (text/x-scss): "/<project>/node_modules/vidstack/player/styles/default/layouts/video.css:410:23": expected selector`. This PR fixes it by removing an extra `,`. This is currently happening in `1.10.3`. I was last using `1.9.8` which didn't have this issue.
Yes
It simply removes an extra `,` from the CSS, so there shouldn't be any significant issues.
> fix: expected selector

- packages/react/src/components/ui/poster.tsx
#1143
The fix in https://github.com/vidstack/player/commit/2684fc3949ace4dc2bd899d47d693d921c026c41 was only targeting the base Vidstack package, I quickly ported it over to the React package.
Yes
> fix(player/react): poster showing broken image icon on load

- packages/vidstack/package.json
Similair to #1196 but now it's for Cloudflare Workers/Pages instead of Deno.
Adds the `workerd` key to the packages conditional exports, so Cloudflare Workers will use the server bundle.
Before it was using the browser bundle which broke my Nuxt 3 site when server-side rendering the Vidstack player.
I've tried to just 1-to-1 matches the changes made for Bun and Deno yesterday.
Yes.
[Cloudflare's docs on the `workerd` exports key](https://developers.cloudflare.com/workers/wrangler/bundling/#conditional-exports)
Before the change it fails like so:
After the change it instead starts the server and you can go to [http://localhost:8788/other-page](http://localhost:8788/other-page) and it loads without throwing any errors.
> fix(player): add workerd to node exports

- packages/vidstack/src/components/ui/sliders/slider-value.ts
Almost the whole player uses the normal percent sign `%` (U+0025) to display percentages.
Except for the `SliderValue` component in which the small percent sign `﹪` (U+FE6A) is used.
Since this character isn't available in many fonts it may look kind of weird:
For consistency and better font compatibility also just the default percent sign should be used:
Yes
> Replace small percent sign with normal one for slider values

- packages/vidstack/player/styles/default/poster.css
I noticed that the poster image displayed before the video plays was not correctly centered (vertically), causing it to appear misaligned, especially on larger screens or within specific container dimensions. This misalignment detracts from the user's initial interaction with the video player.
Yes.
https://www.loom.com/share/29ebae2a91054ca9968172c850a40e68
> Fix: Center Poster Image

- packages/vidstack/mangle.json
- packages/vidstack/src/core/tracks/text/text-tracks.ts
(Hopefully) fixes: https://github.com/vidstack/player/issues/1234
When a captions text track changes to `mode = 'disabled'`, we don't update the `captions: true` flag in LocalStorage to `false`. That means that the enable/disable captions setting is not persisted correctly and isn't carried over when the website refreshes. So, the user has to disable the captions again after every page refresh.
Yes, I think so. I couldn't test it locally though (I'm not a JS developer and have no clue how, sorry!)
> Store disabled captions configuration in LocalStorage.

- packages/vidstack/src/providers/dash/dash.ts
- packages/vidstack/src/utils/language.ts
If no labels are provided, then `track.lang` is chosen as a fallback. Instead, we can use [Intl.DisplayNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames#language_display_names) to get the name of the language by using the language code.
yes
> Improved DASH audio/text track labels

- packages/vidstack/src/player/skins/community/video.css
Removed unnecessary -> **,** <- from CSS
Issue #1258
Yes
> #1258 Remove ','

- packages/react/src/components/layouts/default/slots.tsx
- packages/react/src/components/layouts/default/ui/menus/accessibility-menu.tsx
- packages/react/src/components/layouts/default/ui/menus/audio-menu.tsx
- packages/react/src/components/layouts/default/ui/menus/captions-menu.tsx
- packages/react/src/components/layouts/default/ui/menus/playback-menu.tsx
- packages/react/src/components/layouts/default/ui/menus/settings-menu.tsx
Add slots for the various settings sub-menus, making it possible to add custom settings items to the new settings menu layout in v1.11.
New slots:
```
playbackSettingsMenuStartItems
playbackSettingsMenuEndItems
playbackSettingsMenuLoop
accessibilitySettingsMenuStartItems
accessibilitySettingsMenuEndItems
audioSettingsMenuStartItems
audioSettingsMenuEndItems
captionsMenuStartItems
captionsMenuEndItems
```
Yes.
```tsx
<DefaultVideoLayout
icons={defaultLayoutIcons}
slots={{
beforePlaybackSettingsMenuLoop: (
<DefaultMenuItem label="Autoplay">
<DefaultMenuCheckbox label="Autoplay" />
</DefaultMenuItem>
),
}}
/>
```
> feat(player/react): add default layout slots for settings sub-menus

- packages/vidstack/src/components/player.ts
The `MediaMetadata` API isn't supported universally, so this PR prevents uncaught exceptions by ensuring that the `NavigatorMediaSession` class (which has a dependency on `MediaMetadata`) is not instantiated on browsers without support.
The check is copied from the example on the [`MediaMetadata` MDN page](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession/metadata#example).
Yes
[caniuse.com: MediaMetadata (94.69% global support)](https://caniuse.com/mdn-api_mediametadata)
> fix: Only instantiate `NavigatorMediaSession` in browsers with support for `MediaMetadata`.

- packages/vidstack/src/components/aria/announcer.ts
This PR fixes a race condition affecting the aria-announcer component.
Currently, a `window.setTimeout` function is executed after 300ms to update the label to either "Seek Forward" or "Seek Backward." 
However when the component is unmounted, `$state` is set to null while the timeout is not cleared.
The callback then is executed on an invalid state, attempts to destructure `const { label } = this.$state` resulting in the exception `Cannot destructure property 'label' of 'this.$state' as it is null.`
https://github.com/vidstack/player/blob/08e31f00cd548285dce13bb617d573d676a5dc37/packages/vidstack/src/components/aria/announcer.ts#L99-L115
I hope so
The error appear to be benign and non critical, however it might cause all sort of nasty errors if left uncheck.
I have managed to catch this …
> Fix: Aria-Announcer attemping to set the label on a null $state

- packages/vidstack/src/providers/vimeo/loader.ts
- packages/vidstack/src/providers/vimeo/provider.ts
- packages/vidstack/src/providers/vimeo/utils.ts
https://github.com/vidstack/player/issues/1100
Currently, there are still some issues regarding unlisted Vimeo videos:
- Only videos with URL's using the `hash` path parameter are loaded.
- The `getVimeoVideoInfo` fails when retrieving the video info because the hash isn't provided.
This pr updates the Vimeo provider regex to retrieve to support the hash parameter as `h` (which is used in the embedded URL) or with `video-id>/<video-hash>`.
- `https://vimeo.com/video/<video-id>?h=<video-hash>`
- `https://player.vimeo.com/video/<video-id>/<video-hash>`
Yes.
> Feat: improve unlisted Vimeo video url handling

- packages/react/src/components/ui/poster.tsx
When loading a Poster image using the React API, I noticed react-dom (`19.0.0-beta-26f2496093-20240514`) presented this warning:
> Warning: An empty string ("") was passed to the src attribute. This may cause the browser to download the whole page again over the network. To fix this, either do not render the element at all or pass null to src instead of an empty string.
I found [a writeup of the empty string `src` problem](https://humanwhocodes.com/blog/2009/11/30/empty-image-src-can-destroy-your-site/) from back in 2009(!). So I guess that kind of problem is what the warning is about.
This warning was triggered even if the Vidstack poster component was only ever rendered with a string, so seemed to me unworkaroundable.
I traced this back to this line in the Poster component, which at …
> Set poster image fallback src to undefined, not empty string

- packages/vidstack/src/providers/hls/hls.ts
if a fragment doesnt exist in a hls playlist such as:
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-TARGETDURATION:8
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:7.5,
/doesnt_exist.ts
```
_onNetworkError will call startLoad again on the 404, and the next, etc. causing a ddos of the resource. hls.js handles the retries on its own.
> remove networkError handling

- packages/vidstack/src/core/state/navigator-media-session.ts
**Bug fix** -- When you click the "seek backward" button using a remote control (such as on a smart TV's web browser), it jumps forward instead of backward.  This behavior can be replicated in Chrome using its built-in Media Control feature.
- Open Google Chrome.
- Go to the [demos page](https://www.vidstack.io/player/demo) (or open any Vidstack player on version 1.12.1-next).
- Play the video.
- Click the Media Control button in Chrome, as shown here:
- Click the rewind / "seek backward" button in Chrome's Media Control pop-up, as shown here:
You should see that time has jumped **forward** by 10 seconds.
The expected behavior is that it should jump **backward** by 10 seconds.
> Bug fix; seeking backwards on remote control went forwards in some cases

- packages/vidstack/src/utils/mime.ts
https://github.com/vidstack/player/commit/6801a8402e2bc3f98e9763b920ed1355de48f72b
This fixes the playback of *.m4a files uploaded through Rails/ActiveStorage, as their content type is defined (through the [Marcel](https://github.com/rails/marcel) gem) as `audio/mp4`.
Yes
See discussion - https://discord.com/channels/742612686679965696/1107494438684606554/threads/1271131720061550664
> fix(player): add audio/mp4 mime type

- packages/vidstack/src/providers/google-cast/tracks.ts
N/A
When running Vidstack in a Capacitor app, the app fails to start because of a ReferenceError:
`ReferenceError: chrome is not defined`
This happens because _tracks.ts_ directly references the `chrome` API on import.
This typically doesn't happen when the app is bundled into neatly split dependencies as Vite does by default, but when generating a single bundle that contains the entire app, the `chrome` API will be accessed immediately regardless of the browser used.
This PR prevents the `chrome` API from being referenced early.
Yes
No
> Remove early usage of chrome API

- packages/react/package.json
Issue: https://github.com/vidstack/player/issues/1533
React 19 stable has been released some weeks ago, but @vidstack/react is not yet compatible with it yet.
This also makes it impossible to use it inside NextJS 15 projects.
Dependencies have been upgraded, everything kept working as expected.
Check all functions in the react sandbox example with react 19 and 18.
> feat(react player): allow react ^19.0.0

- packages/vidstack/src/providers/youtube/provider.ts
- packages/vidstack/src/providers/youtube/utils.ts
#1510 #1058 #1571
- It modifies the youtube regex to handle shorts urls by adding an optional, non-matching group.
- It defaults to rel=0 in the video url parameters to hide related videos as a default.
Yes
These are small changes and shouldn't have many (if any) side effects.
- Feed examples of each youtube url (including shorts) into the MediaPlayer component.
- Look for related videos at the end of a youtube video.
> Youtube shorts

- packages/vidstack/src/core/state/media-player-delegate.ts
- packages/vidstack/src/core/state/media-request-manager.ts
- packages/vidstack/src/utils/aria.ts
closes #1479
I already opened an issue and now had time to dig into the code.
When a user has reduced motion settings enabled in their system preferences, the player should respect this setting and not autoplay videos, regardless of the autoplay attribute value. This aligns with accessibility best practices and user preferences for reduced motion.
As a dev we could handle this with a simple check as @ianmiller347 already mentioned in the issue for example. But i think it would be a good practice to implement this directly so it works out of the box.
If the user prefers reduced motion and its autoplaying we throw during the `play` and not `attemptAutoplay` method because the `auto-play-failed` event is triggered by the `play-fail` event. Maybe i overlooked something and this could be …
> Respect user preference for reduced motion when autoplaying

- packages/vidstack/src/core/keyboard/controller.ts
Closes #1462
Feel free to make any changes, thanks.
> fix(player): Ctrl+0 causes a jump to the beginning of the video

- packages/react/src/components/layouts/default/slots.tsx
- packages/react/src/components/layouts/default/ui/time.tsx
I added a missing slot value, `timeDivider `, in the **Default Component**. This slot is already used in the **Time Component**, but it was missing from the **Default Component**, leading to inconsistency in the layout.  
Reference to the relevant code:  
[[Time Component - Line 26](https://github.com/vidstack/player/blob/36cdc06ebb347c786088821ba21ffb96c1334fe5/packages/react/src/components/layouts/default/ui/time.tsx#L26)](https://github.com/vidstack/player/blob/36cdc06ebb347c786088821ba21ffb96c1334fe5/packages/react/src/components/layouts/default/ui/time.tsx#L26)  
```jsx
<DefaultVideoLayout 
icons={defaultLayoutIcons} 
slots={{ timeDivider: ' - ' }} 
/>
```
Yes
> Added timeDivider type to default slots.tsx
